### ISSUE TITLE
Feature request: run shell commands

### ISSUE THREAD

**Issue by Null-Kelvin** [miron9/smtp2communicator#2]
Just for following KISS principle - there is many small tools that can send messages wherever: curl can relay message to any messenger with HTTP API (and most of that messengers even have examples for doing it), go-sendxmpp can relay message to Jabber, etc. Can you add this feature? Something like 
```
channels:
  shell:
    enabled: true
    commandPath: curl
    commandArguments: arguments here
```
Thanks for very useful project anyway
